---
title: "\"Catch\" kann nicht außerhalb einer Try-Anweisung verwendet werden"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 861057ff4d7c68a5917bddbb8d7361946f3f43f5
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 03/15/2019
ms.locfileid: "58041190"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>"Catch" kann nicht außerhalb einer Try-Anweisung verwendet werden
`Catch` muss innerhalb eines `Try...Catch...Finally` -Anweisungsblocks angezeigt werden. Entweder ist die `Catch` -Anweisung im `Try` -Block unnötig, oder die `Catch` -Anweisung befindet sich außerhalb des entsprechenden `Try` -Blocks.  
  
 **Fehler-ID:** BC30380  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1.  Löschen Sie die `Catch` -Anweisung, wenn sie unnötig ist, oder platzieren Sie sie in einem `Try...Catch...Finally` -Anweisungsblock.  
  
## <a name="see-also"></a>Siehe auch

- [Try...Catch...Finally-Anweisung](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
