---
title: "\"Catch\" kann nicht hinter \"Finally\" in einer Try-Anweisung stehen"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: f223eb0520cf625b5e66914188bcadf3ecf9cbd0
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 03/15/2019
ms.locfileid: "58027077"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>"Catch" kann nicht hinter "Finally" in einer Try-Anweisung stehen
Eine `Catch` -Anweisung wird im Code hinter dem `Finally` -Schl√ºsselwort angezeigt, das einen `Try` -Anweisungsblock beendet. `Catch` muss innerhalb eines `Try...Catch...Finally` -Anweisungsblocks angezeigt werden.  
  
 **Fehler-ID:** BC30379  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1.  Verschieben Sie die `Catch` -Anweisung im Code an eine geeignete Position.  
  
## <a name="see-also"></a>Siehe auch

- [Try...Catch...Finally-Anweisung](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
